[env]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
build_flags =
    -I components/dw3000-decadriver-source/platform
    -I components/dw3000-decadriver-source/dwt_uwb_driver
board_build.partitions = partitions.csv
monitor_speed = 115200

[env:tag1]
build_flags = ${env.build_flags} -DBUILD_TAG -DTAG_ID=1
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101

[env:tag2]
build_flags = ${env.build_flags} -DBUILD_TAG -DTAG_ID=2
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101

[env:anchor1]
build_flags = ${env.build_flags} -DBUILD_ANCHOR -DANCHOR_ID=1
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101

[env:anchor2]
build_flags = ${env.build_flags} -DBUILD_ANCHOR -DANCHOR_ID=2
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101

[env:anchor3]
build_flags = ${env.build_flags} -DBUILD_ANCHOR -DANCHOR_ID=3
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101

[env:anchor4]
build_flags = ${env.build_flags} -DBUILD_ANCHOR -DANCHOR_ID=4
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101
